AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config.*'
    - 'config/*'
    - 'config/environments/*'
    - 'Rakefile'
    - 'script/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 100

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 100
